<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
    'Delete' => 'Удалить',
    '*unknown*' => '*неизвестно*',
    '--choose--' => '--выберите--',
    '--no--' => '--нет--',
    '0.5' => '0.5',
    'Id' => 'Id',
    'http://yupe.ru' => 'http://yupe.ru',
    'team@yupe.ru' => 'team@yupe.ru',
    'yupe team' => 'yupe team',
    'Alias' => 'Алиас',
    'Create' => 'Добавление',
    'Record was created!' => 'Запись добавлена!',
    'Record was deleted!' => 'Запись удалена!',
    'Record was changed!' => 'Запись изменена!',
    'Bad characters in {attribute} field' => 'Запрещенные символы в поле {attribute}',
    'Page was not found!' => 'Запрошенная страница не найдена!',
    'Change settings' => 'Изменить настройки',
    'Image' => 'Изображение',
    'Title' => 'Название',
    'Bad request. Please don\'t use similar requests anymore' => 'Неверный запрос. Пожалуйста, больше не повторяйте такие запросы',
    'Description' => 'Описание',
    'Published' => 'Опубликовано',
    'Fields with' => 'Поля, отмеченные',
    'Menu items order' => 'Порядок следования в меню',
    'Change' => 'Редактирование',
    'Parent' => 'Родитель',
    'Status' => 'Статус',
    'Content' => 'Контент',
    'Manage' => 'Управление',
    'Draft' => 'Черновик',
    'create' => 'добавление',
    'are required' => 'обязательны.',
    'manage' => 'управление',
    'Open' => 'Открыт',
    'Close' => 'Закрыт',
    'User' => 'Пользователь',
    'Date' => 'Дата',
    //forum
    'This section describes forum management' => 'В данном разделе представлены средства управления форумами',
    'Do you really want to remove forum?' => 'Вы уверены, что хотите удалить форум?',
    'Create forum' => 'Добавить форум',
    'Create forum and close' => 'Добавить форум и закрыть',
    'Create forum and continue' => 'Добавить форму и продолжить',
    'Find forum' => 'Искать форум',
    'Forums' => 'Форумы',
    'Forums - show' => 'Форумы - просмотр',
    'Forums - edit' => 'Форумы - редактирование',
    'Forums - manage' => 'Форумы - управление',
    'Forum' => 'Форум',
    'Forums - create' => 'Категория - добавление',
    'Short description' => 'Короткое описание',
    'Module for forum management' => 'Модуль для управления форумами сайта',
    'Find forum' => 'Поиск форума',
    'Show forum' => 'Просмотр форума',
    'View forum' => 'Просмотреть форум',
    'Change forum' => 'Редактирование форума',
    'Save forum and close' => 'Сохранить форум и закрыть',
    'Save forum and continue' => 'Сохранить форум и продолжить',
    'Forums list' => 'Список форумов',
    'Remove forum' => 'Удалить форум',
    'Forum manage' => 'Управление форумами',
    'Forum was not found!' => 'Форум не найден!',
    //topic
    'Topic' => 'Тема',
    'Topics' => 'Темы',
    'Topic manage' => 'Управление темами',
    'Topics - manage' => 'Темы - управление',
    'Create topic' => 'Добавить тему',
    'Create topic and close' => 'Добавить тему и закрыть',
    'Create topic and continue' => 'Добавить тему и продолжить',
    'Show topic' => 'Просмотр темы',
    'View topic' => 'Просмотреть тему',
    'Change topic' => 'Редактирование темы',
    'Remove topic' => 'Удалить тему',
    'Do you really want to remove topic?' => 'Вы уверены, что хотите удалить тему?',
    'Save topic and close' => 'Сохранить тему и закрыть',
    'Save topic and continue' => 'Сохранить тему и продолжить',
    //message
    'Message' => 'Сообщение',
    'Messages' => 'Сообщения',
    'Message manage' => 'Управление сообщениями',
    'Messages - manage' => 'Сообщения - управление',
    'Create message' => 'Добавить сообщение',
    'Create message and close' => 'Добавить сообщение и закрыть',
    'Create message and continue' => 'Добавить сообщение и продолжить',
    'Show message' => 'Просмотр сообщения',
    'View message' => 'Просмотреть сообщение',
    'Change message' => 'Редактирование сообщения',
    'Remove message' => 'Удалить сообщение',
    'Do you really want to remove message?' => 'Вы уверены, что хотите удалить сообщение?',
    'Save message and close' => 'Сохранить сообщение и закрыть',
    'Save message and continue' => 'Сохранить сообщение и продолжить',
);
